### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by zvikarp** [yakir8/kosher_dart#1]
hey man this is awesome!

it toke me for ever to find your package and glad i didn't end up making my own because it wouldn't be close to as good your is!

but why not to upload to dart.pub so it would be easier for other to find. or at least add some examples to the readme.

anyway, would suggest to update the instructions in the "Getting Started" section,
" kosher_dart: git: url: https://github.com/yakir8/kosher_dart.git "
to a code block so you can see the indentation because it is important in .yaml files:

```
kosher_dart:
  git:
    url: https://github.com/yakir8/kosher_dart.git
```

and again, thanks for putting this package together! 🎉

**Comment by yakir8** [comment]
Fix thank you
