### ISSUE TITLE
Candle lighting times for second day of Yom Tov is wrong

### ISSUE THREAD

**Issue by tuvia** [yakir8/kosher_dart#10]
Hi, the method getCandleLighting() on class ComplexZmanimCalendar returns the wrong time for candle lighting on second day of Yom Tov. Now it returns 18 minutes before SHKIA but it should return TZEIT HACOCHAVIM time, since candle lighting time for second day of Yom Tov is AFTER first day finishes.

Thank you!!
Tuvia

**Comment by yakir8** [comment]
Hi @tuvia,
Thank you, I commented a fix for this bug.
I am going to publish this to 'pubdart' during this week.
