### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by joekman990** [yakir8/kosher_dart#11]
I don't see anywhere in the documentation a way to format the date to be just the day and month without the year like you can do with the DateFormat in the intl package 

this is a great package thanks

**Comment by moshe5745** [comment]
I think you need to use the HebrewDateFormatter
```
JewishDate date = JewishDate();
  final HebrewDateFormatter _hebrewDateFormatter = HebrewDateFormatter();
_hebrewDateFormatter.formatHebrewNumber(date.getJewishDayOfMonth());

```

This is a greater package indeed

**Comment by yakir8** [comment]
Hi,

I improved format() method from HebrewDateFormatter class, now you can choose whatever  date format you want.
Code exemple
   ```
 HebrewDateFormatter formatter = HebrewDateFormatter();
 formatter.hebrewFormat = true;
 JewishDate jewishDate = JewishDate();
 formatter.format(jewishDate,pattern: "E dd MM yy HH:mm:ss")
```

output
`שני כ״ג טבת תשפ״ב 22:49:29`

Please see method document for more information
