### ISSUE TITLE
Shabbos Entry and Exit Dates

### ISSUE THREAD

**Issue by kishore181995** [yakir8/kosher_dart#13]
Hello @yakir8 

Regarding the Shabbos entry and exit times fetched by the Zmanim Calendar. The entry date is fetching a date that is after the exit date for Shabbos. And also the Shabbos entry date is fetched as Saturday, not Friday. Considering today's date 23-02-2022 the Shabbos entry and exit dates are,

Latitude - 17.6868159.
Longitude - 83.2184815.
Elevation - 54.0
Time Zone Offset -  5:30:00.000000
Current Date - 2022-02-23 13:58:29.072584.

Shabbos Start date 2022-02-27 17:41:46.000  // using the **getShabbosStartTime()** method.
Shabbos Exit date  2022-02-26 18:37:27.000  // using the **getShabbosExitTime()** method.
I have compared the Shabbos entry and exit dates with **[Chabad.org](https://www.chabad.org/calendar/candlelighting_cdo/aid/6226/coords/17.68682%2C83.21848/locationtype/3/n/Visakhapatnam/tdate/2-23-2022/tzname/Asia*Calcutta/jewish/Shabbat-Candle-Lighting-Times.htm)** website.

[Shabbos Issue.txt](https://github.com/yakir8/kosher_dart/files/8122889/Shabbos.Issue.txt)
<img width="509" alt="shabbath issurs" src="https://user-images.githubusercontent.com/19381973/155285162-da66b465-43a7-4ab3-a450-20b34280e60b.PNG">

Could you please let meknow if I am missing anything.

**Comment by yakir8** [comment]
Hi @kishore181995,
Sorry that took me long time to response,
I found bug in my code and fix it on version 2.0.10, now you can update to new version.
Thanks for letting me know about this bug.
