### ISSUE TITLE
Wrong parasha name

### ISSUE THREAD

**Issue by moshe5745** [yakir8/kosher_dart#17]
JewishCalendar jewishCalendar = JewishCalendar.fromDateTime("2022-05-01");
    String parashaTitle =
        _hebrewDateFormatter.formatWeeklyParsha(jewishCalendar);

Output: "Kdoshim".
Expected parashah: "Emor".

**Comment by yakir8** [comment]
Thanks, fixed on verstion 2.0.11
Don't forget set inIsrael to true if your location inside Israel.
