### ISSUE TITLE
Bug Fixme! Error on formatting the date

### ISSUE THREAD

**Issue by lcyper** [yakir8/kosher_dart#22]
![image](https://user-images.githubusercontent.com/4260943/174493304-bb54705f-553e-428a-9594-d1aa2227567a.png)

![image](https://user-images.githubusercontent.com/4260943/174493295-3d2b3b8d-cc1d-4809-8825-325523bdbec7.png)

how to reproduce:
```
DateTime _currentDate = DateTime.now(); // 6/19/2022
final JewishCalendar jewishCalendar =
JewishCalendar.fromDateTime(_currentDate);
HebrewDateFormatter hebrewDateFormatter = HebrewDateFormatter();
String hebrewDate = hebrewDateFormatter.format(jewishCalendar);
```

the problem is when convert the date
```
formatDate = "20 Sivan 5782"
```
now "formatDate" have an "a" so it converts to "PM"
ending formatDate = "20 SivPMn 5782"

file: \kosher_dart-2.0.11\lib\src\hebrewcalendar\hebrew_date_formatter.dart

**Comment by yakir8** [comment]
Fixed on pull request #23 

Thanks
