### ISSUE TITLE
Format error "Nissan" to "Ni00an"

### ISSUE THREAD

**Issue by lcyper** [yakir8/kosher_dart#25]
because of this: (line 644) (\hebrewcalendar\hebrew_date_formatter.dart)

`    if (formatDate.contains("ss")) {
      formatDate = formatDate.replaceAll(
          "ss", DateFormat("ss").format(jewishDate.getGregorianCalendar()));
    }`

**Comment by yakir8** [comment]
Fixed on pull request #22.
Please update to version 2.0.12.
