### ISSUE TITLE
clone method returns wrong date

### ISSUE THREAD

**Issue by lcyper** [yakir8/kosher_dart#31]
```
dateRepository.jewishDate // JewishDate (19 Cheshvan 5783)

dateRepository.jewishDate.clone() // JewishDate (19 Kislev 5783)

```

**Comment by lcyper** [comment]
- i make a [PR](https://github.com/yakir8/kosher_dart/pull/32) to fix this issue.

**Comment by natgross** [comment]
Issue still exists. Latest api - 2.0.12.
clone() has a different date.

**Comment by yakir8** [comment]
@natgross 
I forgot to update the API on pub.dev.
Try now version 2.0.13

**Comment by natgross** [comment]
Yep. It's ok now in 2.0.13
