### ISSUE TITLE
Bug !!!

### ISSUE THREAD

**Issue by dickermoshe** [yakir8/kosher_dart#34]
Adding this to the original KosherJava package was a mistake:
https://github.com/yakir8/kosher_dart/blob/465e2ccab61c06b3deb9dd4937b8b8803d3aa83c/lib/src/zmanim_calendar.dart#L309

The original package does not account whether there is Candle Lighting on that day, or whether to calculate 18 min before sunset on Shabbos or after Tzais on 2nd day Yom Tov or 3-day Yom Tov.

You also don't account for second day Yom Tov outside of the US.
You only reference the possibility of a 2 day yom tov for `JewishCalendar.ROSH_HASHANA`.

Running the following code for the US on April 6th 2023 will crash even though there is candle lighting on that date.
```dart
ComplexZmanimCalendar zmanim = ComplexZmanimCalendar.intGeoLocation(geoLocation);
bool isThereCandleLighting = JewishCalendar.fromDateTime(z.getCalendar()).hasCandleLighting();
if (isThereCandleLighting){
    zmanim.getCandleLighting() // <<-- Will still return null !!!!!
}
```

The complexities of KosherJava are such that any port should try to copy it exactly.

**Comment by yakir8** [comment]
thinks i am closing this the fix is on kosher_dart 2.0.17
