### ISSUE TITLE
Package dependency problem

### ISSUE THREAD

**Issue by YahalomsGuy** [yakir8/kosher_dart#39]
Hello,

I have built an application with your package some time ago and when I returned to it now , Pub Get is failing,
Flutter suggests that the problem is because of dependency on intl packge version 0.17, which is outdated (current version is 0.18.1)

Sine I am working with Flutter version >3.00 and with a Flutter Localization package that requires intl package version 0.18, the app cannot run.

Are there any intensions on your side to upgrade the Kosher_Dart package so it will support the latest version of intl?

**Comment by elishao** [comment]
had the same issue. for now I downloaded kosher_dart and changed it to 0.18.1 locally

**Comment by natgross** [comment]
Bump issue

**Comment by yakir8** [comment]
Fixed on version 2.0.14

**Comment by natgross** [comment]
Same issue - new version. intl 0.19
