### ISSUE TITLE
Daily prayer times doesn't change with date

### ISSUE THREAD

**Issue by L035568** [yakir8/kosher_dart#4]
Hello,
I'm using the kosher_dart package in one of the flutter mobile app, where I intend to show the daily prayer time to users based on their geolocation. The anomaly that I witness is "events for day doesn't show changes based on user selection".

The code is pretty simple where I create a GeoLocation object (location) based on Latitude, Longitude, Elevation and current DateTime. There after I use the location object to create ComplexZmaninCalendar object to get different prayer time along with sunrise and sunset. 

The sunrise,sunset and prayer times doesn't change even though the I move the selected date ahead by months. Ideally there should be delta changes in minutes by changing the months. I 

//Create GeoLocation Object.
GeoLocation location = new GeoLocation();
    location.setLatitude(latitude: 37.77);
    location.setLongitude(longitude: -122.73);
    location.setElevation(215);
    location.setDateTime(_dateTime); // Current DateTime

//Calendar Object
ComplexZmanimCalendar zc =
        new ComplexZmanimCalendar.intGeoLocation(location);

DateTime startOfDay = zc.getSunrise();
    DateTime endOfDay = zc.getSunset();

print('SUNRISE: $startOfDay');
print('SUNSET : $endOfDay');

**Comment by yakir8** [comment]
Hi @asifiqbalgh ,

Follow this code:

```
    DateTime _dateTime = DateTime.now();
    //Create GeoLocation Object.
    GeoLocation location = new GeoLocation();
    location.setLatitude(latitude: 37.77);
    location.setLongitude(longitude: -122.73);
    location.setElevation(215);
    location.setDateTime(_dateTime); // Current DateTime

    //Calendar Object
    ComplexZmanimCalendar zc =
    new ComplexZmanimCalendar.intGeoLocation(location);

    DateTime startOfDay = zc.getSunrise();
    DateTime endOfDay = zc.getSunset();

    print('SUNRISE: $startOfDay');
    print('SUNSET : $endOfDay');
    print('After months');
    _dateTime = _dateTime.add(Duration(days: 30));
    location.setDateTime(_dateTime); // After months DateTime
    zc.setGeoLocation(location);
    startOfDay = zc.getSunrise();
    endOfDay = zc.getSunset();
    print('SUNRISE: $startOfDay');
    print('SUNSET : $endOfDay');
```
