### ISSUE TITLE
wrong jewish date for january 1 2021 computed by lib

### ISSUE THREAD

**Issue by farid327** [yakir8/kosher_dart#5]
Hi

why kosher_dart compute wrong value for January 01 2021 until December 31 2021?
16 teves compute twice on December 31 and January 01 and next days. **(2020 is a Leap Year)**

Thanks.

**Comment by yakir8** [comment]
hi @farid327

Are you working with the last commit? I fix this issues.
If you are working with the last commit, please share the code you are running.

**Comment by farid327** [comment]
I use version 2.0.1 from pub.dev. It is published in this version?

**Comment by yakir8** [comment]
not yet, I need to update the version in pub.dev. 
Hope to update by the end of the week.

**Comment by farid327** [comment]
Thanks. i will use code from repo :)
i faced with other bugs too so I'll report this bugs to You.
Happy Hanukah :+1:

**Comment by yakir8** [comment]
The version on pub.dev update to 2.0.2
