### ISSUE TITLE
intl version workaround

### ISSUE THREAD

**Issue by natgross** [yakir8/kosher_dart#6]
When I add `kosher_dart: ^2.0.2` to pubspec.yaml, 'flutter get' reports:

_Because kosher_dart >=2.0.2 depends on intl ^0.17.0-nullsafety.2 and my_project_a depends on intl ^0.16.1, kosher_dart >=2.0.2 is forbidden._

If I then try to use the intl pre-release version with '^0.17.0-nullsafety.2' in pubspec, 'flutter get' reports:

_Because every version of flutter_localizations from sdk depends on intl 0.16.1 and my_project_a depends on intl ^0.17.0-nullsafety.2, flutter_localizations from sdk is forbidden._

Any ideas on a workaround please?

**Comment by yakir8** [comment]
Now version 2.0.3 support null safety.
Please upgrade kosher_dart to this version.
