### ISSUE TITLE
Add null Safety.

### ISSUE THREAD

**Issue by j-j-gajjar** [yakir8/kosher_dart#7]
Plugin project :kosher_dart not found. Please update settings.gradle.
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:kosher_dart

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by yakir8** [comment]
Now version 2.0.3 support null safety.
